# Generated by Django 5.2.5 on 2025-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BAJA CLOUDS', max_length=200)),
                ('subtitle', models.CharField(default='coming soon', max_length=200)),
                ('on_air_text', models.CharField(default='ON AIR', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coming Soon Page',
                'verbose_name_plural': 'Coming Soon Pages',
            },
        ),
    ]
