# Generated by Django 5.2.5 on 2025-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoonpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
